version: '3'
services:
  gatling:
    image: gatling
    container_name: gatling
    privileged: true
    volumes:
      - ./gatling_workdir/results:/gatling/results
      - ./gatling_workdir/simulations:/gatling/user-files/simulations
    working_dir: /gatling
    stdin_open: true
    tty: true
    command: /bin/sh
